# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 721, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setStyleSheet("#frame{\n"
"background : url( C:/Users/akira/Downloads/p.jpg);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushDescargar = QtWidgets.QPushButton(self.frame)
        self.pushDescargar.setGeometry(QtCore.QRect(540, 50, 81, 31))
        self.pushDescargar.setObjectName("pushDescargar")
        self.texUrl = QtWidgets.QTextEdit(self.frame)
        self.texUrl.setGeometry(QtCore.QRect(40, 50, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.texUrl.setFont(font)
        self.texUrl.setObjectName("texUrl")
        self.tableDescargas = QtWidgets.QTableWidget(self.frame)
        self.tableDescargas.setGeometry(QtCore.QRect(0, 120, 721, 371))
        self.tableDescargas.setObjectName("tableDescargas")
    
        self.tableDescargas.setColumnCount(0)
        self.tableDescargas.setRowCount(0)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YT Download"))
        self.pushDescargar.setText(_translate("MainWindow", "Descargar"))
        self.texUrl.setPlaceholderText(_translate("MainWindow", "Introducir la url del video"))
        self.tableDescargas.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
