# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialogo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.tableFormato = QtWidgets.QTableWidget(Dialog)
        self.tableFormato.setGeometry(QtCore.QRect(0, 0, 321, 201))
        self.tableFormato.setObjectName("tableFormato")
        self.tableFormato.setColumnCount(0)
        self.tableFormato.setRowCount(0)
        self.pushAceptar = QtWidgets.QPushButton(Dialog)
        self.pushAceptar.setGeometry(QtCore.QRect(30, 210, 75, 23))
        self.pushAceptar.setObjectName("pushAceptar")
        self.pushCancelar = QtWidgets.QPushButton(Dialog)
        self.pushCancelar.setGeometry(QtCore.QRect(190, 210, 75, 23))
        self.pushCancelar.setObjectName("pushCancelar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Seleccione un formato"))
        self.pushAceptar.setText(_translate("Dialog", "Aceptar"))
        self.pushCancelar.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
